import argparse
import csv
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont


def load_rgb(path):
    return Image.open(path).convert("RGB")


def crop_and_zoom(img, crop, size):
    x, y, w, h = crop
    patch = img.crop((x, y, x + w, y + h))
    return patch.resize((size, size), Image.Resampling.BICUBIC)


def fit_image(img, target_w, target_h):
    scale = min(target_w / img.width, target_h / img.height)
    new_w = max(1, int(img.width * scale))
    new_h = max(1, int(img.height * scale))
    return img.resize((new_w, new_h), Image.Resampling.BICUBIC), scale


def draw_label_center(draw, box, text, font):
    x0, y0, x1, y1 = box
    bbox = draw.textbbox((0, 0), text, font=font)
    tw = bbox[2] - bbox[0]
    th = bbox[3] - bbox[1]
    draw.text((x0 + (x1 - x0 - tw) / 2, y0 + (y1 - y0 - th) / 2), text, fill=(0, 0, 0), font=font)


def find_lq(gt_path, lq_dir):
    gt_path = Path(gt_path)
    lq_dir = Path(lq_dir)
    stem = gt_path.stem
    candidates = [
        lq_dir / f"{stem}x2.png",
        lq_dir / f"{stem}_LRBI_x2.png",
        lq_dir / f"{stem}.png",
    ]
    for path in candidates:
        if path.exists():
            return path
    matches = sorted(lq_dir.glob(f"{stem}*.png"))
    if matches:
        return matches[0]
    raise FileNotFoundError(f"Cannot find LR image for {gt_path.name} in {lq_dir}")


def load_best_row(csv_path, rank):
    with Path(csv_path).open("r", encoding="utf-8") as f:
        rows = list(csv.DictReader(f))
    if not rows:
        raise RuntimeError(f"No rows found in {csv_path}")
    idx = rank - 1
    if idx < 0 or idx >= len(rows):
        raise IndexError(f"rank={rank} is out of range; csv has {len(rows)} rows")
    return rows[idx]


def save_layout(tiny_path, ssgr_path, gt_path, lq_path, crop, out_path, crop_display_size, overview_width, overview_height):
    tiny = load_rgb(tiny_path)
    ssgr = load_rgb(ssgr_path)
    gt = load_rgb(gt_path)
    lq = load_rgb(lq_path)

    if tiny.size != gt.size:
        tiny = tiny.resize(gt.size, Image.Resampling.BICUBIC)
    if ssgr.size != gt.size:
        ssgr = ssgr.resize(gt.size, Image.Resampling.BICUBIC)
    bicubic = lq.resize(gt.size, Image.Resampling.BICUBIC)

    margin = 24
    gap = 18
    label_h = 28
    patch_size = crop_display_size
    right_cols = 2
    right_rows = 2
    right_w = right_cols * patch_size + (right_cols - 1) * gap
    right_h = right_rows * (patch_size + label_h) + (right_rows - 1) * 10
    canvas_w = margin * 2 + overview_width + gap + right_w
    canvas_h = margin * 2 + max(overview_height + label_h, right_h)

    canvas = Image.new("RGB", (canvas_w, canvas_h), (255, 255, 255))
    draw = ImageDraw.Draw(canvas)
    font = ImageFont.load_default()
    draw.line((margin, 8, canvas_w - margin, 8), fill=(0, 0, 0), width=2)

    overview, scale = fit_image(gt, overview_width, overview_height)
    ov_x = margin + (overview_width - overview.width) // 2
    ov_y = margin
    canvas.paste(overview, (ov_x, ov_y))
    draw.rectangle((ov_x, ov_y, ov_x + overview.width - 1, ov_y + overview.height - 1), outline=(40, 40, 40), width=1)

    x, y, w, h = crop
    rx0 = ov_x + int(x * scale)
    ry0 = ov_y + int(y * scale)
    rx1 = ov_x + int((x + w) * scale)
    ry1 = ov_y + int((y + h) * scale)
    draw.rectangle((rx0, ry0, rx1, ry1), outline=(230, 0, 0), width=3)
    draw_label_center(draw, (ov_x, ov_y + overview.height, ov_x + overview.width, ov_y + overview.height + label_h), "HR Image", font)

    labels = ["Bicubic", "MaIR-Tiny", "MaIR-Tiny+SSGR", "GT"]
    imgs = [bicubic, tiny, ssgr, gt]
    start_x = margin + overview_width + gap
    start_y = margin
    for idx, (label, img) in enumerate(zip(labels, imgs)):
        row = idx // right_cols
        col = idx % right_cols
        px = start_x + col * (patch_size + gap)
        py = start_y + row * (patch_size + label_h + 10)
        patch = crop_and_zoom(img, crop, patch_size)
        canvas.paste(patch, (px, py))
        draw.rectangle((px, py, px + patch_size - 1, py + patch_size - 1), outline=(30, 30, 30), width=1)
        draw_label_center(draw, (px, py + patch_size, px + patch_size, py + patch_size + label_h), label, font)

    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    canvas.save(out_path)


def main():
    parser = argparse.ArgumentParser(
        description="Create paper-style layout from best_patches.csv generated by find_best_sr_visual_examples.py."
    )
    parser.add_argument("--csv", required=True, help="best_patches.csv path.")
    parser.add_argument("--rank", type=int, default=1, help="Which ranked crop to use, starting from 1.")
    parser.add_argument("--lq-dir", required=True, help="LR_bicubic/X2 directory.")
    parser.add_argument("--out", required=True, help="Output figure path.")
    parser.add_argument("--crop-display-size", type=int, default=150)
    parser.add_argument("--overview-width", type=int, default=420)
    parser.add_argument("--overview-height", type=int, default=330)
    args = parser.parse_args()

    row = load_best_row(args.csv, args.rank)
    tiny_path = Path(row["tiny_path"])
    ssgr_path = Path(row["ssgr_path"])
    gt_path = Path(row["gt_path"])
    lq_path = find_lq(gt_path, args.lq_dir)
    crop = (int(row["x"]), int(row["y"]), int(row["size"]), int(row["size"]))

    save_layout(
        tiny_path,
        ssgr_path,
        gt_path,
        lq_path,
        crop,
        args.out,
        args.crop_display_size,
        args.overview_width,
        args.overview_height,
    )
    print(f"Using rank {args.rank}: {row['name']} crop={crop}")
    print(f"LQ: {lq_path}")
    print(f"Saved: {args.out}")


if __name__ == "__main__":
    main()
